Gabriel Marcelino, Grant Burk, and Eli Kaustinen
September 2024
Artificial Neural Network (ANN)

## Import dependencies and load data

In [121]:
import sys
print(sys.path)


['C:\\Program Files\\JetBrains\\PyCharm 2023.3.3\\plugins\\python\\helpers-pro\\jupyter_debug', 'C:\\Program Files\\JetBrains\\PyCharm 2023.3.3\\plugins\\python\\helpers\\pydev', 'C:\\Users\\grant\\PycharmProjects\\neural-networks', 'C:\\Users\\grant\\AppData\\Local\\Programs\\Python\\Python312\\python312.zip', 'C:\\Users\\grant\\AppData\\Local\\Programs\\Python\\Python312\\DLLs', 'C:\\Users\\grant\\AppData\\Local\\Programs\\Python\\Python312\\Lib', 'C:\\Users\\grant\\AppData\\Local\\Programs\\Python\\Python312', '', 'C:\\Users\\grant\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages', 'C:\\Users\\grant\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\win32', 'C:\\Users\\grant\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\win32\\lib', 'C:\\Users\\grant\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\Pythonwin', 'C:\\Users\\grant\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\setuptools\\_vendor']


In [122]:
import csv
import random
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import tensorflow as tf
from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

pool = []
training_data = []
# create pool with players from 2019-2022
with open('all_seasons.csv', mode = 'r') as file:
    csvFile = csv.reader(file)
    # ignore first line
    next(csvFile)
    for lines in csvFile:
        training_data.append(lines)


## Optimal Team : Considerations
For my optimal team, I will aim for:
- 1 or more players in top 20% of shooting percentage.
- Player in the top 5% out of the 100 for rebounds.
- Player with a Defensive Rebound percentage bigger than 0.2
- 3 or more players in top 20% of best net rating
- 2 or more players with better than average assists

In [123]:
def extract_features(player):
    return {
        'name': player[1],
        'ts_pct': float(player[19]),
        'reb': float(player[13]),
        'dreb_pct': float(player[17]),
        'rating': float(player[15]),
        'ast': float(player[14])
    }


In [124]:
def team_score(team):
    ts_pct = np.mean([player['ts_pct'] for player in team])
    reb = np.sum([player['reb'] for player in team])
    dreb_pct = np.max([player['dreb_pct'] for player in team])
    rating = np.mean([player['rating'] for player in team])
    ast = np.sum([player['ast'] for player in team])
    # For my optimal team, the most important features are
    # 1. True shooting percentage
    # 2. Defensive rebound percentage
    # 3. Rating
    # 4. Assists/Rebounds
    score = (ts_pct * 20 + reb * 0.5 + dreb_pct * 10 + rating + ast * 0.5) / 5
    return score

def select_optimal_team(pool, team_size=5):
    player_features = [extract_features(player) for player in pool]
    
    best_team = None
    best_score = -float('inf')

    # Use a heuristic to find a good solution
    for _ in range(1000):  # Number of iterations
        team = random.sample(player_features, team_size)
        score = team_score(team)
        if score > best_score:
            best_score = score
            best_team = team

    return best_team, best_score





## Model

In [125]:
def extract_features(pool):
    features_list = []
    for player in pool:
        # extract relevant features based on considerations above
        features = {
            'name': player[1],
            'ts_pct': player[19],
            'reb': player[13],
            'dreb_pct': player[17],
            'rating': player[15],
            'ast': player[14]
        }
        features_list.append(features)
    return features_list


## Simulate Training Data to train model

In [126]:
def make_empty(player):
    player['ts_pct'] = 0
    player['reb'] = 0
    player['dreb_pct'] = 0
    player['rating'] = 0
    player['ast'] = 0
    return player

# Get Best Player for Category

In [127]:
def get_best(players, category):
    best_index = 0
    for cur in range(len(players)):
        if float(players[cur][category]) > float(players[best_index][category]):
            best_index = cur
    return best_index

# Pre Process the data

In [128]:
def get_datapool(segment):
    # Make testing data sets
    Xall = extract_features(training_data)
    
    # Create one training set
    X1 = []
    for i in range(100):
        X1.append(Xall[i + segment * 100])
        
    Xval = []
    for player in X1:
        Xval.append(np.array([float(player['ts_pct']), float(player['reb'])/100, float(player['dreb_pct']), float(player['rating'])/100, float(player['ast'])/100])) # extract values + normalizations 
    Xval = np.array(Xval)
    
    tempX1 = []
    for player in X1:
        tempX1.append(player.copy())
    
    # Create empty expected Y array to fill later
    Y1 = np.empty_like(X1)
    for i in range(len(Y1)):
        Y1[i] = 0
    
    # Best ts_pct into Y1
    cur = get_best(tempX1, 'ts_pct')
    tempX1[cur] = make_empty(tempX1[cur]) # Prevent repeat
    Y1[cur] = 1
    
    # Best reb into Y1
    cur = get_best(tempX1, 'reb')
    tempX1[cur] = make_empty(tempX1[cur]) # Prevent repeat
    Y1[cur] = 1
    
    # Best dreb_pct into Y1
    cur = get_best(tempX1, 'dreb_pct')
    tempX1[cur] = make_empty(tempX1[cur]) # Prevent repeat
    Y1[cur] = 1
    
    # Best rating into Y1
    cur = get_best(tempX1, 'rating')
    tempX1[cur] = make_empty(tempX1[cur]) # Prevent repeat
    Y1[cur] = 1
    
    # Best ast into Y1
    cur = get_best(tempX1, 'ast')
    tempX1[cur] = make_empty(tempX1[cur]) # Prevent repeat
    Y1[cur] = 1
    
    Y1 = np.array(Y1)
    
    print()
    print("Y1")
    print(len(Y1))
    print(Y1)
    
    Y1temp =  tf.convert_to_tensor(Y1, dtype=tf.float64)
    print()
    print("Y1temp")
    print(len(Y1temp))
    print(Y1temp)
    
    print()
    print("Xval")
    print(len(Xval))
    print(Xval)
    
    Xvaltemp =  tf.convert_to_tensor(Xval, dtype=tf.float64)
    print()
    print("Xvaltemp")
    print(len(Xvaltemp))
    print(Xvaltemp)
    
    return X1, Xvaltemp, Y1temp # return raw X (X1), processed X (Xval), and Y value (Y1

X_raw_train, X_train, y_train = get_datapool(1)
X_raw_test, X_test, y_test = get_datapool(2)


Y1
100
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]

Y1temp
100
tf.Tensor(
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.], shape=(100,), dtype=float64)

Xval
100
[[ 5.44e-01  6.20e-02  1.57e-01  4.50e-02  2.50e-02]
 [ 4.86e-01  2.20e-02  1.55e-01 -7.30e-02  6.00e-03]
 [ 6.45e-01  4.00e-02  1.06e-01 -4.90e-02  4.10e-02]
 [ 4.86e-01  1.70e-02  8.80e-02 -1.14e-01  1.60e-02]
 [ 5.54e-01  1.03e-01  2.07e-01  3.40e-02  4.60e-02]
 [ 5.66e-01  1.30e-02  9.30e-02  2.00e-02  2.20e-02]
 [ 5.62e-01  8.80e-02  1.86e-01  1.10e-01  2.70e-02]
 [ 5.52e-01  2.10e-02  1.77e-01 -5.90e-02  4.00e

# Print Player Pools

In [129]:
print("Training Team:")
print(X_raw_train)
print()
print("Testing Team:")
print(X_raw_test)

Training Team:
[{'name': 'Chris Mills', 'ts_pct': '0.544', 'reb': '6.2', 'dreb_pct': '0.157', 'rating': '4.5', 'ast': '2.5'}, {'name': 'Chris Morris', 'ts_pct': '0.486', 'reb': '2.2', 'dreb_pct': '0.155', 'rating': '-7.3', 'ast': '0.6'}, {'name': 'Chris Mullin', 'ts_pct': '0.645', 'reb': '4.0', 'dreb_pct': '0.106', 'rating': '-4.9', 'ast': '4.1'}, {'name': 'Chris Robinson', 'ts_pct': '0.486', 'reb': '1.7', 'dreb_pct': '0.08800000000000001', 'rating': '-11.4', 'ast': '1.6'}, {'name': 'Chris Webber', 'ts_pct': '0.5539999999999999', 'reb': '10.3', 'dreb_pct': '0.207', 'rating': '3.4', 'ast': '4.6'}, {'name': 'Chris Whitney', 'ts_pct': '0.5660000000000001', 'reb': '1.3', 'dreb_pct': '0.09300000000000001', 'rating': '2.0', 'ast': '2.2'}, {'name': 'Christian Laettner', 'ts_pct': '0.562', 'reb': '8.8', 'dreb_pct': '0.18600000000000003', 'rating': '11.0', 'ast': '2.7'}, {'name': 'Chucky Brown', 'ts_pct': '0.552', 'reb': '2.1', 'dreb_pct': '0.177', 'rating': '-5.9', 'ast': '0.4'}, {'name': 'Chr

## Train Model
Now that we have the training data, we can train the model.

In [130]:
# 3. Neural Network Model
model = tf.keras.models.Sequential([
    # Input Layer (implicitly present by specifying input_shape)
    
    # Hidden Layer 1
    tf.keras.layers.Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    
    # Hidden Layer 2
    tf.keras.layers.Dense(64, activation='relu'),
    
    # Output Layer
    tf.keras.layers.Dense(2, activation='softmax')  # Two categories
])

# 4. Compile the Model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# 5. Train the Model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))


Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.6231 - loss: 0.6803 - val_accuracy: 0.9500 - val_loss: 0.6201
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9600 - loss: 0.6064 - val_accuracy: 0.9500 - val_loss: 0.5602
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9382 - loss: 0.5551 - val_accuracy: 0.9500 - val_loss: 0.5130
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9632 - loss: 0.4984 - val_accuracy: 0.9500 - val_loss: 0.4677
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9600 - loss: 0.4539 - val_accuracy: 0.9500 - val_loss: 0.4208
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9569 - loss: 0.4063 - val_accuracy: 0.9500 - val_loss: 0.3737
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9538 - loss: 0.3653 - val_accuracy: 0.9500 - val_loss: 0.3295
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9569 - loss: 0.3138 - val_accuracy: 0.9500 - val_loss: 0.2908


# Print Team

In [131]:
print("Actual Best Team:")
for i in range(len(y_test)):
    if(y_test[i] == 1):
        print(X_raw_test[i])
print()
print("Predicted Best Team:")
predicted_y = model.predict(X_test)
print(predicted_y)
for i in range(len(predicted_y)):
    if(predicted_y[i][0] > 0.94):
        print(X_raw_test[i]['name'])


Actual Best Team:
{'name': "Shaquille O'Neal", 'ts_pct': '0.556', 'reb': '12.5', 'dreb_pct': '0.26', 'rating': '6.9', 'ast': '3.1'}
{'name': 'Rod Strickland', 'ts_pct': '0.5329999999999999', 'reb': '4.1', 'dreb_pct': '0.09300000000000001', 'rating': '1.7', 'ast': '8.9'}
{'name': 'Will Perdue', 'ts_pct': '0.5820000000000001', 'reb': '9.8', 'dreb_pct': '0.25', 'rating': '-4.7', 'ast': '0.6'}
{'name': 'Steve Scheffler', 'ts_pct': '0.799', 'reb': '0.4', 'dreb_pct': '0.077', 'rating': '-19.9', 'ast': '0.0'}
{'name': 'Litterial Green', 'ts_pct': '0.531', 'reb': '0.5', 'dreb_pct': '0.055', 'rating': '17.0', 'ast': '0.9'}

Predicted Best Team:
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step 
[[0.8710036  0.1289964 ]
 [0.8827924  0.11720757]
 [0.8804651  0.11953498]
 [0.8539028  0.1460972 ]
 [0.8747458  0.12525429]
 [0.83034    0.16966003]
 [0.8896331  0.11036687]
 [0.88491553 0.11508451]
 [0.8884005  0.11159955]
 [0.879187   0.12081301]
 [0.8897122  0.11028782]
 [0.87737954 0.12262046]
 [0.8625058  0.137

## Explain your architecture and how the basketball player characteristics are used as inputs:

1. Data Preparation:

- Pool and Training Data:
    - Separates data: 
        - `pool` holds 100 unique players (2019-2022) for potential future use.
        - `training_data` stores up to 5000 players (2019-2022) for model training.

2. Feature Extraction:

- The `extract_features` function takes a list of players and creates a dictionary of features for each one. 
- These features include:
    - Name (not used as input)
    - True Shooting Percentage (ts_pct)
    - Rebounds (reb)
    - Defensive Rebound Percentage (dreb_pct)
    - Net Rating (rating)
    - Assists (ast)

3. Simulating Data for Training:

- The `simulate_data` function generates training data with labels indicating successful teams based on pre-defined criteria.
- It takes a list of players (`sample`) and a number of simulations (`num_iter`).
- Here's how player characteristics are used as inputs:
    - Averages and percentiles are calculated for assists, shooting percentage, rebounds, and net rating from the `sample` data.
    - Loops through `num_iter` simulations:
        - Selects 5 random players.
        - Extracts their features using `extract_features`.
        - Assigns a label (0 or 1) based on the criteria defined above..

4. Model Building and Training:

TO-DO
5. Evaluation:

TO-DO


## Interpret the output of your MLP in the context of selecting an optimal basketball team:

This MLP is trained on the 'optimal' prediction, given the input features of the dataset-shooting percentage, rebounds, assists, and player ratings amongst others-a basketball lineup is optimal. These mentioned inputs provide key indications about player performance. The model will process it for a binary outcome; 1 stands for an optimum team, and 0 stands for a suboptimum team. It could be shown that the MLP model is currently trained to learn from historical data to understand whether a combination of players is strong or weak and thus provide insight into which lineups will perform likely perform.

These could then inform the choice of an optimum basketball team, where the model shows which sets of players are statistically balanced in key performance metrics. The teams that are predicted as "optimal" will indicate that their set of players is effective, while those labeled "suboptimal" need adjustment. Coaches or team selectors would be able to play around with different mixes of players in order to fine-tune their strategy and ensure the team is great in a lot of aspects of the game: scoring, defense, teamwork, just to name a few.

Besides the precision, recall is one of the metrics that signifies model reliability or accuracy. High accuracy means the model can discriminate between good and bad lineups well. While precision and recall give an indication of few false predictions or missing optimal teams, in the end, what an MLP model provides is a data-driven method of selection of the team so as to best ensure that the lineup chosen will perform better on the court.